#find_package("reg_data" REQUIRED PATHS ${ROOT_PATH} PATH_SUFFIXES project/modules)

#set(EXECUTABLE_DIR "${CMAKE_BINARY_DIR}/${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
set(SHARED_LIBRARY_DIR ".")
set(MODULE_LIBRARY_DIR ".")

set(INSTALL_EXECUTABLE "${CMAKE_PROJECT_NAME}")
set(INSTALL_SHARED_LIBRARY ".")
set(INSTALL_MODULE_LIBRARY ".")