# Find GSL
# GSL_FOUND
# GSL_INCLUDE_DIR
# GSL_LIBRARIES

find_path(GSL_INCLUDE_DIR gsl/gsl_errno.h)
find_library(GSL_LIBGSL NAMES gsl)
find_library(GSL_LIBGSLCBLAS NAMES gslcblas)

if (GSL_INCLUDE_DIR AND GSL_LIBGSL AND GSL_LIBGSLCBLAS)
	set(GSL_FOUND TRUE)
	set(GSL_LIBRARIES ${GSL_LIBGSL} ${GSL_LIBGSLCBLAS})
	if (NOT GSL_FIND_QUIETLY)
		message(STATUS "Found GSL: ${GSL_INCLUDE_DIR} ${GSL_LIBRARIES}")
	endif (NOT GSL_FIND_QUIETLY)
else (GSL_INCLUDE_DIR AND GSL_LIBGSL AND GSL_LIBGSLCBLAS)
	if (GSL_FIND_REQUIRED)
		message(FATAL_ERROR "GSL not found")
	endif (GSL_FIND_REQUIRED)
endif (GSL_INCLUDE_DIR AND GSL_LIBGSL AND GSL_LIBGSLCBLAS)