function(collection_test)
	#Выполняется для автоматизированной системы сборки
  if(AUTO_BUILD STREQUAL YES)
    if(DEFINED ${PROJECT_NAME}_LIBRARY)
      #Поиск файла тестового проекта
      find_file(${PROJECT_NAME}_TEST CMakeLists.txt PATHS ${ROOT_PATH}/${${PROJECT_NAME}_LIBRARY}/test NO_DEFAULT_PATH)
      if(NOT ${${PROJECT_NAME}_TEST} STREQUAL ${PROJECT_NAME}_TEST-NOTFOUND)
        set(CURRENT_TESTS ${PROJECT_NAME}_test)
        set(${CURRENT_TESTS}_LIBRARY ${ROOT_PATH}/${${PROJECT_NAME}_LIBRARY}/test)
        add_subdirectory(${${CURRENT_TESTS}_LIBRARY} ${CMAKE_BINARY_DIR}/subproject/${CURRENT_TESTS})
        #add_dependencies(${PROJECT_NAME} ${CURRENT_TESTS})
      endif(NOT ${${PROJECT_NAME}_TEST} STREQUAL ${PROJECT_NAME}_TEST-NOTFOUND)
    endif(DEFINED ${PROJECT_NAME}_LIBRARY)
   endif(AUTO_BUILD STREQUAL YES)
endfunction(collection_test)
	
function(add_collection_test)
	if(DEFINED GROUP_TESTS)
		set(${PROJECT_NAME}_GROUP_TESTS ${GROUP_TESTS})
		unset(GROUP_TESTS)
		if(NOT DEFINED ${PROJECT_NAME}_LIBRARY)
			message(FATAL_ERROR "Error in ${CURRENT_TESTING}-config.cmake. Variable ${CURRENT_TESTING}_LIBRARY not defined!")
			return()
		endif(NOT DEFINED ${PROJECT_NAME}_LIBRARY)
		foreach(CURRENT_TEST ${${PROJECT_NAME}_GROUP_TESTS})
			set(${CURRENT_TEST}_LIBRARY ${${PROJECT_NAME}_LIBRARY}/${CURRENT_TEST})
			add_subdirectory(${${CURRENT_TEST}_LIBRARY} ${CMAKE_BINARY_DIR}/subproject/${CURRENT_TEST})
		endforeach(CURRENT_TEST ${${PROJECT_NAME}_GROUP_TESTS})
	endif(DEFINED GROUP_TESTS)
endfunction(add_collection_test)
